server:
  port: 8090
  # 授权服务和客户端在同一个域名下会出现authorization_request_not_found错误 session=null 方案1 使用不同地址 2 修改session名称
  servlet:
    session:
      cookie:
        name: s1
logging:
  level:
    org:
      springframework: INFO