server:
  port: 8085
  # 授权服务和客户端在同一个域名下会出现authorization_request_not_found错误 session=null 方案1 使用不同地址 2 修改session名称
  servlet:
    session:
      cookie:
        name: s4

logging:
  level:
    org:
      springframework: INFO
    com:
      alibaba:
        nacos: ERROR


spring:
  security:
    oauth2:
      client:
        registration:
          auth-login:
            client-name: auth-login
            provider: uaa
            client-id: login
            client-secret: login
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/sys"
            scope: all
          login:
            client-name: app
            provider: uaa
            client-id: app
            client-secret: app
            authorization-grant-type: password
            scope: all
        provider:
          uaa:
            authorization-uri: http://192.168.0.173:8090/oauth/authorize
            token-uri: http://192.168.0.173:8090/oauth/token
            user-info-uri: http://192.168.0.173:8090/user
            user-name-attribute: name
            jwk-set-uri: http://192.168.0.173:8090/token_keys

