spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: ALWAYS #控制台彩色输出

    #  # Redis服务器地址
#  redis:
#    port: 6379
#    host: 127.0.0.1
#    # Redis服务器连接密码（默认为空）
#    #    database:
#    password: root
    #    # 连接池最大连接数（使用负值表示没有限制）
    #    lettuce:
    #      pool:
    #        max-active: 100
    #        # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-wait: 6000
    #        # 连接池中的最大空闲连接
    #        max-idle: 100
    #        # 连接池中的最小空闲连接
    #        min-idle: 10
    #    # 连接超时时间（毫秒）
    #    timeout: 2000
    # redis.cluster
#    cluster:
#      nodes: 172.17.0.3:6379
#      max-redirects: 8
#    sentinel:
#      nodes:

#security:
#  oauth2:
#    client:
#      clientId: acme
#      clientSecret: acmesecret
#      authorized-grant-types: authorization_code,refresh_token,password
#      scope: openid

logging:
  level:
    org:
      #      springframework: TRACE
      springframework: INFO
    io.lettuce.core: ERROR
    #      springframework: DEBUG
    com:
      alibaba:
        nacos: ERROR